- name: Install Zabbix Agent
  hosts: windows
  gather_facts: False
  tasks:

  - name: Create Temporary Directory to Download Zabbix Agent Package
    win_tempfile:
      state: directory
      suffix: zabbix-agent
    register: temp

  - name: Download Zabbix Agent Package and checksum
    win_get_url:
      url: https://www.zabbix.com/downloads/5.0.1/zabbix_agent-5.0.1-windows-amd64.zip
      dest: "{{ item }}\\zabbix_agent.zip"
      checksum: 552cff6e3d794d790d1e27e6de33e368fb0bbe45
      checksum_algorithm: sha1
      force: True
    with_items:
      - "{{ temp.path }}"

  - name: Unzip Zabbix Agent Package
    win_unzip:
      src: "{{ item }}\\zabbix_agent.zip"
      dest: C:\zabbix_agent
    with_items:
      - "{{ temp.path }}"

  - name: Remove Temporary Directory
    win_file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ temp.path }}"

  - name: Create Config File from a Jinja2 template
    win_template:
      src: templates/zabbix_agentd.conf.j2
      dest: C:\zabbix_agent\conf\zabbix_agentd.conf

  - name: Install Zabbix Agent Service
    win_shell: C:\zabbix_agent\bin\zabbix_agentd.exe -c C:\zabbix_agent\conf\zabbix_agentd.conf -i

  - name: Start Zabbix Agent Service
    win_shell: C:\zabbix_agent\bin\zabbix_agentd.exe -s


